# Generated by Django 3.2.7 on 2021-12-23 12:10

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=300)),
                ('Description', ckeditor.fields.RichTextField()),
                ('Trailer', models.CharField(max_length=250)),
                ('Download_link', models.CharField(max_length=233)),
                ('Director', models.CharField(max_length=233)),
                ('Writer', models.CharField(max_length=233)),
                ('Star_Cast', models.CharField(max_length=400)),
                ('genres', models.CharField(max_length=300)),
                ('Realese_Date', models.DateField()),
                ('Run_time', models.IntegerField()),
                ('Plot_keywords', models.CharField(max_length=233)),
                ('Poster', models.ImageField(upload_to='')),
                ('Created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
