# Generated by Django 3.2.7 on 2021-12-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmovie',
            name='Description',
            field=models.TextField(),
        ),
    ]
