# Generated by Django 3.2.7 on 2021-12-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_newmovie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmovie',
            name='Featured',
            field=models.BooleanField(default=False),
        ),
    ]
