# Generated by Django 3.2.7 on 2021-12-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_newmovie_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmovie',
            name='Coming_Soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newmovie',
            name='Rating',
            field=models.FloatField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='newmovie',
            name='Sample1',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='newmovie',
            name='Sample2',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='newmovie',
            name='Sample3',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
