# Generated by Django 3.2.7 on 2021-12-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211225_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmovie',
            name='Rating',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='newmovie',
            name='Sample1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='newmovie',
            name='Sample2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='newmovie',
            name='Sample3',
            field=models.ImageField(upload_to=''),
        ),
    ]
