# Generated by Django 4.0.1 on 2022-02-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220104_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmovie',
            name='webSearies',
            field=models.BooleanField(default=False),
        ),
    ]
